### ISSUE TITLE
Hi,PixnBits,could you find the way to resolve delay piping on SoX stderr?

### ISSUE THREAD

**Issue by arrowing** [PixnBits/sox-play#2]
I want to get information from SoX stderr but that is so delay.
I'm very doubt in this quesion.

I see a function names 'guessPosition' that you provide.
:(

**Comment by PixnBits** [comment]
Sorry for the delay
I created this for a side project that didn't get too far past, well, this package, so I didn't get to see how performant this approach actually was :-(.
There may be a better way to get data from sox, but I hadn't invested the time yet.
I've wanted to come back to this but have other pressing time constraints, sorry :-(.

**Comment by arrowing** [comment]
I see.
I close this issue.
Good luck to you.
